In [ ]:
# comes under data preperation and sampling

In [ ]:
# how do you prepare input text?

'''
1- splitting text into individual word and subword tokens
2- convert these token into token id
3- encode token ID's into vector representations

 '''

In [ ]:
# tokens can be character, pieces of words or full words

text = "I'm learning tokenization"

character_tokens = ['I', '’', 'm', ' ', 'l', 'e'] # <--many tokens
word_tokens = ['I’m', 'learning', 'tokenization', '!'] #<- fewer tokens, but OOV risk -> out of vocab -> chatgptnizer
subword_tokens= ['I', '’', 'm', ' learn', 'ing', ' token', 'ization', '!'] # <- used in modern LLM's

# Creating Tokens

## *-load and read db*

In [ ]:
with open('/content/drive/MyDrive/4. Data Files/LLM Dataset/the verdict.txt','r',encoding='utf-8') as f:
  data = f.read()

In [ ]:
print(len(data)) # <-- length of data
data[:99]

20482


'I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no '

## *-splitting words*

In [ ]:
import re # <-- we will use regular expression to split the long texts

text = 'Hello, this is my -- data!?""'

def split_func(text):
  preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
  preprocessed = [p.strip() for p in preprocessed if p.strip()] # if p.strip() removes blank
  return preprocessed


In [ ]:
split_func(text)

['Hello', ',', 'this', 'is', 'my', '--', 'data', '!', '?', '"', '"']

In [ ]:
# should we remove widespaces or not ?
'''
depends on application and recuirements
-> reduces memory and computing requirements
-> we keep in in cases where structure is required -> python indentation & spaces
 '''

In [ ]:
preprossed = split_func(data)
len(preprossed)

4827

## *- building vocab*

In [ ]:
# small vocab -> many unknowns, slow training worse quality because long dependency

In [ ]:
# concept enumerate
l=['Kunal', 'Bharat', 'Wagh']
enumerate(l) # <- this is enemurate object which adds counter to each element
for index, item in enumerate(l):
  print(index,item)

0 Kunal
1 Bharat
2 Wagh


dict_items([('name', 'Kunal'), ('age', 25), ('gender', 'male')])

In [ ]:
# encoding ->

# unique elements and sort it and then assign the token
preprossed # <- splitted data

In [ ]:
sorted_data = sorted(set(preprossed))
len(sorted_data)
sorted_data

['!',
 '"',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 ':',
 ';',
 '?',
 'A',
 'Ah',
 'Among',
 'And',
 'Are',
 'Arrt',
 'As',
 'At',
 'Be',
 'Begin',
 'Burlington',
 'But',
 'By',
 'Carlo',
 'Chicago',
 'Claude',
 'Come',
 'Croft',
 'Destroyed',
 'Devonshire',
 'Don',
 'Dubarry_',
 'Emperors',
 'Florence',
 'For',
 'Gallery',
 'Gideon',
 'Gisburn',
 'Gisburns',
 'Grafton',
 'Greek',
 'Grindle',
 'Grindles',
 'HAD',
 'Had',
 'Hang',
 'Has',
 'He',
 'Her',
 'Hermia',
 'His',
 'How',
 'I',
 'If',
 'In',
 'It',
 'Jack',
 'Jove',
 'Just',
 'Lord',
 'Made',
 'Miss',
 'Money',
 'Monte',
 'Moon',
 'Mr',
 'Mrs',
 'My',
 'Never',
 'No',
 'Now',
 'Nutley',
 'Of',
 'Oh',
 'On',
 'Once',
 'Only',
 'Or',
 'Perhaps',
 'Poor',
 'Professional',
 'Renaissance',
 'Rickham',
 'Riviera',
 'Rome',
 'Russian',
 'Sevres',
 'She',
 'Stroud',
 'Strouds',
 'Suddenly',
 'That',
 'The',
 'Then',
 'There',
 'They',
 'This',
 'Those',
 'Though',
 'Thwing',
 'Thwings',
 'To',
 'Usually',
 'Venetian',
 'Victor',
 'Was',
 '

In [ ]:
vocab = {token:integer for integer,token in enumerate(sorted_data)} # use enemurate
vocab

{'!': 0,
 '"': 1,
 "'": 2,
 '(': 3,
 ')': 4,
 ',': 5,
 '-': 6,
 '.': 7,
 ':': 8,
 ';': 9,
 '?': 10,
 'A': 11,
 'Ah': 12,
 'Among': 13,
 'And': 14,
 'Are': 15,
 'Arrt': 16,
 'As': 17,
 'At': 18,
 'Be': 19,
 'Begin': 20,
 'Burlington': 21,
 'But': 22,
 'By': 23,
 'Carlo': 24,
 'Chicago': 25,
 'Claude': 26,
 'Come': 27,
 'Croft': 28,
 'Destroyed': 29,
 'Devonshire': 30,
 'Don': 31,
 'Dubarry_': 32,
 'Emperors': 33,
 'Florence': 34,
 'For': 35,
 'Gallery': 36,
 'Gideon': 37,
 'Gisburn': 38,
 'Gisburns': 39,
 'Grafton': 40,
 'Greek': 41,
 'Grindle': 42,
 'Grindles': 43,
 'HAD': 44,
 'Had': 45,
 'Hang': 46,
 'Has': 47,
 'He': 48,
 'Her': 49,
 'Hermia': 50,
 'His': 51,
 'How': 52,
 'I': 53,
 'If': 54,
 'In': 55,
 'It': 56,
 'Jack': 57,
 'Jove': 58,
 'Just': 59,
 'Lord': 60,
 'Made': 61,
 'Miss': 62,
 'Money': 63,
 'Monte': 64,
 'Moon': 65,
 'Mr': 66,
 'Mrs': 67,
 'My': 68,
 'Never': 69,
 'No': 70,
 'Now': 71,
 'Nutley': 72,
 'Of': 73,
 'Oh': 74,
 'On': 75,
 'Once': 76,
 'Only': 77,
 'Or': 78,

## *- building tokenizer*

In [ ]:
# concept dict.items()
d = {
    'name' : 'Kunal',
    'age' : 25,
    'gender' : 'male'
}
d.items()

In [ ]:
# tokenizer class
# will have encode method and decode method

class SimpleTokenv1:

  def __init__(self, vocab):
    self.str_to_int = vocab # <- this is -> ['apple':1, 'banana':2]
    self.int_to_str = {i: s for s, i in vocab.items()} # this is [1:'apple', 2:'banana'] # <- derived attribute

  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [p.strip() for p in preprocessed if p.strip()] # if p.strip() removes blank
    ids = [self.str_to_int[s] for s in preprocessed]
    return ids

  def decode(self, ids):
    text = " ".join(self.int_to_str[i] for i in ids)
    # # remove spaces before normal punctuation
    text = re.sub(r'\s+([,.:;?!()"\'\]])', r'\1', text)
    return text



In [ ]:
tokenizer = SimpleTokenv1(vocab)

text = "I ,HAD always 'thought', Jack Gisburn, rather a, cheap!!"


k = tokenizer.encode(text)
k

[53, 5, 44, 163, 2, 1021, 2, 5, 57, 38, 5, 835, 129, 5, 271, 0, 0]

In [ ]:
tokenizer.decode(k)

"I, HAD always' thought', Jack Gisburn, rather a, cheap!!"

### *- words not in vocab*

In [ ]:
text = 'Hello My name is Kunal'
# tokenizer.encode(text) # <-- it will throw error as some words not exist

# this means we need to have large vocabulary to accomodate each word ->
# one approch is to add context tokens other we will discuss later

In [ ]:
# context tokens
#  <|unk|>    -> for unknown words in vocab
# <|endoftext|>   -> for markers are end of text/document for seperation


# depending on LLM researchers also considers
# [BOS] -> begining of sequence -> start of text
# [EOS] -> end of sequence
# [PAD] -> padding -> short text padded upto longest text

# GPT -> <|endoftext|> but not use <|unk|> instead use Byte pair Encoding

In [ ]:
sorted_data.extend(['<|unk|>','<|endoftext|>'])

In [ ]:
sorted_data[-5:]

['yourself', '<|unk|>', '<|endoftext|>', '<|unk|>', '<|endoftext|>']

In [ ]:
# update the vocab
vocab = {token:integer for integer,token in enumerate(sorted_data)} # use enemurate

In [ ]:
list(vocab.items())[-5:]

[('younger', 1145),
 ('your', 1146),
 ('yourself', 1147),
 ('<|unk|>', 1150),
 ('<|endoftext|>', 1151)]

In [ ]:
# we will modify our token generator ->

class SimpleTokenv2:

  def __init__(self, vocab):
    self.str_to_int = vocab # <- this is -> ['apple':1, 'banana':2]
    self.int_to_str = {i: s for s, i in vocab.items()} # this is [1:'apple', 2:'banana'] # <- derived attribute

  def encode(self, text):
    preprocessed = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preprocessed = [p.strip() for p in preprocessed if p.strip()] # if p.strip() removes blank
    preprocessed = [item if item in self.str_to_int else '<|unk|>' for item in preprocessed] # <- updated
    ids = [self.str_to_int[s] for s in preprocessed]
    return ids

  def decode(self, ids):
    text = " ".join(self.int_to_str[i] for i in ids)
    # remove spaces before normal punctuation
    text = re.sub(r'\s+([,.:;?!()"\'\]])', r'\1', text)
    return text


In [ ]:
text = 'Hello My name is Kunal'

tokenizer = SimpleTokenv2(vocab)
k = tokenizer.encode(text)
k

[1150, 68, 1150, 598, 1150]

In [ ]:
tokenizer.decode(k)

'<|unk|> My <|unk|> is <|unk|>'

In [ ]:
text1 = 'Hello do you like Tea?'
text2 = 'my name is kunal'

text = " <|endoftext|> ".join((text1,text2))
text

'Hello do you like Tea? <|endoftext|> my name is kunal'

In [ ]:
k = tokenizer.encode(text)
k

[1150, 374, 1144, 640, 1150, 10, 1151, 711, 1150, 598, 1150]

In [ ]:
tokenizer.decode(k)

'<|unk|> do you like <|unk|>? <|endoftext|> my <|unk|> is <|unk|>'

### *- Summery*

## Byte pair encoding

In [ ]:
# use to train GPT-2, GPT-3

In [ ]:
# algorithms

'''
1. word based -> every word is token

- my hobby is to play cricket => ['my','hobby','is','to','play','cricket']
-> out of vocab words -> boy and boys are different and simialirity is not captured

#---------------------------------------------------------------------

2/ character based -> each character is token

- my name is kunal -> ['','','','','','','',...]
-> small vocab size and out of vocab will not problem
-> meaning associated is lost
-> tokenized sequence is much longer than raw text -> text -1 & token-more

#---------------------------------------------------------------------

3/ subword based ->

rule1 = donot split frequently used words into smaller subwords
rule2 = split rare words into smaller, meaning subwords -> required -> dropdown to character

boy and boys -> boy should not split and boys -> boy + s


-> helps model understand that different word with same root word are similar in meaning
--> token, tokens, tokinizing are all same

-> helps model to understand that tokinization and modernization are made up of
differnt root word but have same suffix 'ization' and used in same syntactic situations

 '''

In [ ]:
# BPE is subword tokenization algorithm
# introduced 1994

# https://www.semanticscholar.org/paper/A-new-algorithm-for-data-compression-Gage/1aa9c0045f1fe8c79cce03c7c14ef4b4643a21f8

'''
- most common pair of consecutive byte(2) of data is replace it with byte
that doesnot occur in data

aaabdaaabac => aa with z
zabdzabac => ab with y
zydzyac => compressed data => we can go another layer -> zy to w
wdwc
 '''


'\n- most common pair of consecutive byte(2) of data is replace it with byte\nthat doesnot occur in data\n\naaabdaaabac => aa with z\nzabdzabac => ab with y\nzydzyac => compressed data => we can go another layer -> zy to w\nwdwc\n '

In [ ]:
# BPE ->
# 1/ most common words in vocab is represented as single word
# 2/ rare words are broken down into subwords

In [ ]:
# preprocessing -
'''
- old 7, older 3, finest 9, lowest 4
#---------------------------------------------------
preprocessing -> each token with ending </w>

- old</w> 7, older</w> 3, finest</w> 9, lowest</w> 4
#---------------------------------------------------
setep/1 -> split words into characters and make frequency table

</w> -> 23
o -> 14
l -> 14
d -> 10
e -> 16
r -> 3
f -> 9
i -> 9
n -> 9
s -> 13
t -> 13
w -> 4

#-------------------------------------------------------------------------------
step/2 -> most frequent character -> e check it's pairing

er -> 3
es -> 13

# merge these tokens

</w> -> 23
o -> 14
l -> 14
d -> 10
e -> 16 ==> remove 13 -> 3
r -> 3
f -> 9
i -> 9
n -> 9
s -> 13 ==> remove 13 -> 0 => s always appeares with e
t -> 13
w -> 4
es -> 13

#-------------------------------------------------------------------------------
#setp/3 -> check if this new token merges with something or not

est -> 13

# merge these tokens

</w> -> 23
o -> 14
l -> 14
d -> 10
e -> 3
r -> 3
f -> 9
i -> 9
n -> 9
t -> 13 ==> remove 13 -> 0
w -> 4
es -> 13 ==> remove 13 -> 0
est -> 13 # <-- common root word

#-------------------------------------------------------------------------------
step/4

est</w> -> 13  -> important to understand the position of words

merge this token

</w> -> 23 ==> remove 13 -> 10
o -> 14
l -> 14
d -> 10
e -> 3
r -> 3
f -> 9
i -> 9
n -> 9
w -> 4
est -> 13 ==> remove 13 -> 0
est</w> -> 13  -> gets information as est</w> always comes at end -> ending sequence -> statement ends here

#-------------------------------------------------------------------------------

step/5 ol pair occurs most

ol -> 10 times


</w> -> 10
o -> 14 ==> remove 10 -> 4
l -> 14 ==> remove 10 -> 4
d -> 10
e -> 3
r -> 3
f -> 9
i -> 9
n -> 9
w -> 4
est</w> -> 13
ol -> 10

#-------------------------------------------------------------------------------

step/6

old -> 10

</w> -> 10
o -> 4
l -> 4
d -> 10 ==> remove 10 -> 0
e -> 3
r -> 3
f -> 9
i -> 9
n -> 9
w -> 4
est</w> -> 13
ol -> 10 ==> remove 10 -> 0
old -> 10 -> captured root word


-> here f,i,n also exist but not in diverse so we will not modify that

#-------------------------------------------------------------------------------
# new generated vocab ->

est</w>
old
</w>
o
l
e
r
f
i
n
w
#-------------------------------------------------------------------------------

# stopping criteria will either be token count or number of iterations

-> solves out of vocabulary problems and root meanings are captured

 '''

## *- bite pair incoder for openAI models*



In [ ]:
!pip install tiktoken

In [ ]:
import importlib
import tiktoken

importlib.metadata.version('tiktoken') # <-- version

'0.12.0'

In [ ]:
tokenizer = tiktoken.get_encoding('gpt2') # <-- get the vocab and encoding for gpt2
# same as our simpletokenizer class -> encode and decode method

In [ ]:
text = 'Hello my name is Kunal <|endoftext|> and I like someunknownfeeling'
encoded_text = tokenizer.encode(text,allowed_special={'<|endoftext|>'})
encoded_text
# someunknownfeeling -> split into subwords
# token 50257 -> token limit of gpt2 -> english has 170000-2000000 words


[15496,
 616,
 1438,
 318,
 509,
 18835,
 220,
 50256,
 290,
 314,
 588,
 617,
 34680,
 5036,
 10809]

In [ ]:
decoded_text = tokenizer.decode(encoded_text)
decoded_text

'Hello my name is Kunal <|endoftext|> and I like someunknownfeeling'

## dealing with unknown tokens

In [ ]:
unk_tok = tokenizer.encode('Akdfffdghlkr erstrsd') #<- does BPE
print(unk_tok)

dec_unk = tokenizer.decode(unk_tok)
print(dec_unk)

[33901, 67, 487, 16344, 456, 75, 38584, 1931, 2536, 21282]
Akdfffdghlkr erstrsd


## tokenizers and their use case

In [ ]:
# this will consist of types of tokenizers used in different kind of language models and comparision

#--

# *input - target pairs*

In [ ]:
# autoregressive model

'''
model predicts one word at a time ->

This
This is                           <- this become input to next iteration
This is some                      <- 'some' is predicted
This is some facinating
this is some facinating stuff

# this is self supervised learning and auto_regressive

 '''
 # we will mask out all the words which is suppose to be predicted

In [ ]:
with open('/content/drive/MyDrive/4. Data Files/LLM Dataset/the verdict.txt','r',encoding='utf-8') as f:
  raw_text = f.read()

In [ ]:
import tiktoken

In [ ]:
tokenizer = tiktoken.get_encoding('gpt2')

In [ ]:
encoded_text = tokenizer.encode(raw_text)
print(len(encoded_text)) # <- vocab size
print(encoded_text)

5147
[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11, 290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536, 5469, 438, 14363, 938, 4842, 1650, 353, 438, 2934, 489, 3255, 465, 48422, 540, 450, 67, 3299, 13, 366, 5189, 1781, 340, 338, 1016, 284, 3758, 262, 1988, 286, 616, 4286, 705, 1014, 510, 26, 475, 314, 836, 470, 892, 286, 326, 11, 1770, 13, 8759, 2763, 438, 1169, 2994, 284, 943, 17034, 318, 477, 314, 892, 286, 526, 383, 1573, 11, 319, 9074, 13, 536, 5469, 338, 11914, 11, 33096, 663, 4808, 3808, 62, 355, 996, 484, 547, 12548, 287, 281, 13079, 410, 12523, 

In [ ]:
# context size -> how many words as input to get the output

In [ ]:
encoded_sample = encoded_text[50:]

In [ ]:
context_size = 4

# model is trained to look for 4 words and then predict
# how much words model should pay attention at one time
'''
x = [1,2,3,4]
y = [2,3,4,5]

1 -> 2
12 -> 3
123 -> 4
1234 -> 5

 '''

x = encoded_sample[:context_size]
y = encoded_sample[1:context_size+1]

print('x',x)
print('y',y)

x [290, 4920, 2241, 287]
y [4920, 2241, 287, 257]


In [ ]:
for i in range(1,context_size+1):

  input = encoded_sample[:i]
  desired = encoded_sample[i]

  print(f'{input} --> {desired}')
  print(f'{tokenizer.decode(input)} --> {tokenizer.decode([desired])}')
  print('-'*50)

[290] --> 4920
 and -->  established
--------------------------------------------------
[290, 4920] --> 2241
 and established -->  himself
--------------------------------------------------
[290, 4920, 2241] --> 287
 and established himself -->  in
--------------------------------------------------
[290, 4920, 2241, 287] --> 257
 and established himself in -->  a
--------------------------------------------------


## dataset and dataloader in pytorch

In [ ]:
# we need to convert it into more structured format and in tensor (pytorch)
# -> tensor -> multidimensional array
'''
1 -> input tensor which llm sees
2 -> output tensor for llm to predict

 '''

'\n1 -> input tensor which llm sees\n2 -> output tensor for llm to predict\n\n '

In [ ]:
# we will use pytorch's built-in dataset and dataloader classes

'''
fetches the input output target pairs using sliding window approch -> slide the input

we collect inputs in tensor x where each row represents input context

x = tensor([
  ['in','the','heart','of'],        #<-- each similar row is input -> has 4 prediction tasks -> context is 4
  ['the','city','stood','the'],
  ['old','library',',','a']
])



y = tensor([
  ['the','heart','of','the'],   #<-- each similar row is output ->
  ['city','stood','the','old'],
  ['library',',','a','relitic']
])


 '''




In [ ]:
# will be done in 4 steps
'''
1/ tokenize entire text
2/ using sliding window to chunk the book into overlapping sequence of max length
3/ return total numbers of rows in dataset
4/ return single row in dataset

 '''

'''
 below is the Dataset class
 #-> defines how rows are fetched from dataset
 #->

  '''

'\n below is the Dataset class\n #-> defines how rows are fetched from dataset \n #->\n\n  '

In [ ]:
import torch
import tiktoken
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):

  def __init__(self,text,tokenizer,max_length,stride):
    self.input_ids =[]
    self.target_ids = []

    # tokenize the entire text
    token_ids = tokenizer.encode(text,allowed_special={'<|endoftext|>'})

    # use sliding window approch to chunk book into overlapping sequence of max_length

    for i in range(0,len(token_ids)-max_length,stride): # <- range(start,end,jump)

      input_chunk = token_ids[i:i+max_length] # <-- getting chunks one by one by index
      target_chunk = token_ids[i+1 : i+max_length+1]

      self.input_ids.append(torch.tensor(input_chunk)) #<-- converting those chunks to pytorch chunks
      self.target_ids.append(torch.tensor(target_chunk))
#-------------------------------------------------------------------------------------------------------

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, idx): # <-- dataloder requires this method <- to fetch one by one
    return self.input_ids[idx],self.target_ids[idx] #<-- returns the id's of tensors


In [ ]:
k= torch.tensor([1,2,3,4])
l = torch.tensor([2,3,4,5])
print(k)
print(l)

t = []

t.append(k)
t.append(l)
t

tensor([1, 2, 3, 4])
tensor([2, 3, 4, 5])


[tensor([1, 2, 3, 4]), tensor([2, 3, 4, 5])]

In [ ]:
# following code will use the GPTDatasetV1 to load the inputs in batches via PyTorch DataLoader

In [ ]:
'''
# steps ->

1/ initialize dataset
2/ create dataset
3/ drop_last = True. Drops the last batch if shorter than specified batch_size to prevent spikes during training
4/ The number of CPU processes to use for preprocessing

- helps for parallel processing
- analyze multiple batches at same time

batch_size => number of batches model process at once before updating it's parameters
num_workers => parallel processing

 '''

In [ ]:
def crate_dataloader_v1(txt,batch_size=4,max_length=256,
                        stride=128, shuffle=True, drop_last=True,
                        num_workers=0):

  #initialize the tokenizer
  tokenizer = tiktoken.get_encoding('gpt2')

  # Create Dataset
  dataset = GPTDatasetV1(txt,tokenizer,max_length,stride)

  # crate dataloder
  dataloder = DataLoader(
      dataset,  # <-- dataset contains training and test tensors
      batch_size=batch_size, # <-- size of tensors
      shuffle=shuffle, # <-- True
      drop_last=drop_last, # <-- True
      num_workers=num_workers # <-- 0
  )

  return dataloder


In [ ]:
 # testing dataloader with batch size 1 and context of 4

In [ ]:
with open('/content/drive/MyDrive/4. Data Files/LLM Dataset/the verdict.txt','r',encoding='utf-8') as f:
  raw_text = f.read()

In [ ]:
# convert the dataloader into python iterator to fetch next entry via python's next function

In [ ]:
import torch

dataloader = crate_dataloader_v1(raw_text,batch_size=1,max_length=4,
                                 stride=1, shuffle=False)
data_iter = iter(dataloader)

first_batch = next(data_iter)
print(first_batch) # <-- get input tensor and output tensor
second_batch = next(data_iter)
print(second_batch) # <-- stride = 1 means 1 shifting

[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]
[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [ ]:
# as max length is set to 4 -> each tensors stores 4 token id's
# in gpt it usually takes 256

'''
# -> batch size 1 is for illustration purposes -> small batches requires less memory
but lead to more noicy model updates
--> batch size is tradeoff and need to set a good parameter (hyperparameter)

 '''

In [ ]:
# batch size more than 1

dataloader = crate_dataloader_v1(raw_text,batch_size=8,max_length=4,
                                 stride=1, shuffle=False)
data_iter = iter(dataloader)

first_batch = next(data_iter)
print(first_batch)
second_batch = next(data_iter)
print(second_batch)

# input tensor has 8 inputs



[tensor([[   40,   367,  2885,  1464],
        [  367,  2885,  1464,  1807],
        [ 2885,  1464,  1807,  3619],
        [ 1464,  1807,  3619,   402],
        [ 1807,  3619,   402,   271],
        [ 3619,   402,   271, 10899],
        [  402,   271, 10899,  2138],
        [  271, 10899,  2138,   257]]), tensor([[  367,  2885,  1464,  1807],
        [ 2885,  1464,  1807,  3619],
        [ 1464,  1807,  3619,   402],
        [ 1807,  3619,   402,   271],
        [ 3619,   402,   271, 10899],
        [  402,   271, 10899,  2138],
        [  271, 10899,  2138,   257],
        [10899,  2138,   257,  7026]])]
[tensor([[10899,  2138,   257,  7026],
        [ 2138,   257,  7026, 15632],
        [  257,  7026, 15632,   438],
        [ 7026, 15632,   438,  2016],
        [15632,   438,  2016,   257],
        [  438,  2016,   257,   922],
        [ 2016,   257,   922,  5891],
        [  257,   922,  5891,  1576]]), tensor([[ 2138,   257,  7026, 15632],
        [  257,  7026, 15632,   438],
    

In [ ]:
'''
# we increase stride to 4 to utilize data fully(we don't skip a single word)
but also provide any overlap between batches since more overlap could lead to
increase overfitting

 '''

#--

# Token Embeddings

In [ ]:
# vector embedding
# not word embedding -> can include subwords

In [ ]:
'''
Representing words numerically ->

1/ random numbers -> will not get the true reletionships between numbers

CNN -> encode special reletion between the pixels to predict -> exploit the info.
#-------------------------------------------------------------------------------

2/ one hot encoding -> fails to get symentic reletionship 1000000100010001000100

#------------------------------------------------------------------------------

3/ vector encoding -> every word is vector
-> dimension is determined by feature


# Features: [has_a_tail, is_eatable, has_4_legs, makes_sound, is_a_pet]

dog     = [23,  2, 19, 12, 35]
cat     = [31,  3, 21, 18, 31]
apple   = [1,  22,  0, 0.5, 5]
banana  = [2,  38,  0, 0.2, 7]

for similar features both dog and cat are closer and same for apple and banana

 '''

In [ ]:
# how to make this vector embedding ?

'''
we need to train neural network for this

 '''

## *demo*

In [ ]:
# demo ->

# many companies has already a pre trained model like - word2vec https://huggingface.co/fse/word2vec-google-news-300
# 300 is dimension


In [ ]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 73.6 MB/s eta 0:00:00


In [ ]:
import gensim.downloader as api

model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [ ]:
word_vectors = model # <--- it is basically dictionary with words and their vectors

In [ ]:
word_vectors['man'] #<-- indexing dict item

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
# similar words ->
word_vectors.most_similar(positive=['father','daughter'],negative=['son'],topn=10)

[('mother', 0.8948175311088562),
 ('niece', 0.8004239201545715),
 ('eldest_daughter', 0.7821366786956787),
 ('grandmother', 0.780648410320282),
 ('aunt', 0.7747992277145386),
 ('granddaughter', 0.771183967590332),
 ('sister', 0.7706005573272705),
 ('husband', 0.7571515440940857),
 ('wife', 0.7549542784690857),
 ('daughters', 0.7524171471595764)]

In [ ]:
# Example of calculating similarity
print(word_vectors.similarity('woman', 'man'),'# <-- high relation')
print(word_vectors.similarity('king', 'queen'),'# <-- high relation')
print(word_vectors.similarity('Instagram', 'Facebook'),'# <-- high relation')
print(word_vectors.similarity('boy', 'girl'),'# <-- high relation')
print(word_vectors.similarity('rock', 'tree'),'# <-- low relation')
print(word_vectors.similarity('paper', 'water'),'# <-- low relation')


0.76640123 # <-- high relation
0.6510957 # <-- high relation
0.55903774 # <-- high relation
0.8543272 # <-- high relation
0.1536612 # <-- low relation
0.11408084 # <-- low relation


In [ ]:
# most similar words

word_vectors.most_similar('Ronaldo',topn=4)

[('Cristiano_Ronaldo', 0.8814299702644348),
 ('Ronaldinho', 0.8581245541572571),
 ('Robinho', 0.8249523043632507),
 ('Messi', 0.8209547996520996)]

In [ ]:
# so basically vector encodes the meaning

# how token embedding are created in LLM

In [ ]:
  # gpt 2 -> vocab = 50257 and dimension

In [ ]:
import numpy as np
# Vocabulary size (rows) and vector dimension (columns)
vocab_size = 10      # small example instead of 50257
embed_dim  = 30       # small example instead of 768

# Create a random "embedding matrix"
E = np.random.randn(vocab_size, embed_dim)

print("Embedding matrix shape:", E.shape)
print("Rows = token IDs, Columns = vector dimensions\n")

# Print matrix with headers
header = ["tok_id"] + [f"d{j}" for j in range(embed_dim)]
print("  ".join(f"{h:>6}" for h in header))

for i in range(vocab_size):
    row_vals = "  ".join(f"{v:6.2f}" for v in E[i])
    print(f"{i:6d}  {row_vals}")


Embedding matrix shape: (10, 30)
Rows = token IDs, Columns = vector dimensions

tok_id      d0      d1      d2      d3      d4      d5      d6      d7      d8      d9     d10     d11     d12     d13     d14     d15     d16     d17     d18     d19     d20     d21     d22     d23     d24     d25     d26     d27     d28     d29
     0   -0.72   -0.56   -0.84   -0.83   -0.62    0.19    0.87    0.46   -0.33    2.05   -1.02    0.63   -0.15    0.29   -0.94    2.58    2.02    0.42    0.33   -0.26    2.21    0.64   -0.87    0.51    1.95    0.19   -1.28    0.06    1.06   -2.49
     1   -0.06   -0.93   -0.27   -1.67    0.05   -0.64    0.90   -0.02    0.33   -1.15    0.10   -1.74   -0.23    0.43    0.96   -1.12    1.14    1.12   -1.97    0.02   -0.62    0.98    0.06   -1.30   -2.85   -1.85   -0.79    0.32    1.73   -0.51
     2   -0.94    1.61   -0.10    1.04    0.31    0.02   -1.75    0.22   -2.07   -0.07   -0.84    0.51    0.22   -1.62    2.26    0.02   -0.45    1.46    1.01   -0.17    1.13   -0

In [ ]:
'''

-1/ we initialize embedding weights with random values
-2/ initialization will work as a starting point for LLM learning
-3/ embedding weights are then optimized as part of LLM training

---> based on training data
---> backpropogation is implemented

=> so basically we perform 2 training one for GPT and other for embedding matrix


 '''

# initialization for embedding matrix

In [ ]:
import torch

In [ ]:
# simplocity we will use small vocab of 6 tokens and embedding of size 3
'''
for each token we will have 3 dimensional vector
'''
vocab_size = 6
output_dim = 3

torch.manual_seed(123)

embedding_layer = torch.nn.Embedding(vocab_size,output_dim) # why called lookup table?
embedding_layer

Embedding(6, 3)

In [ ]:
embedding_layer.weight # initialized the weights randomly

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)

In [ ]:
# consist of small random values which later then optimized via LLM training

# to get vector for id_level 3 ->

embedding_layer(torch.tensor([3])) # <- ecactly like dictionary lookup #<- lookup operation

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)

In [ ]:
input_ids = torch.tensor([2,3,5,1])
embedding_layer(input_ids) # <-- returns the embedding matric for those IDs

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)

In [ ]:
# embedding layer is same as neural network linear layer

# -> embedding layer is computationally efficient since NN linear layer has many unnecessary multiplication
#___ with zero

# torch.nn.linear() #<- not efficient

#---

# Positional Embedding

In [ ]:
'''
- till now we have learned how to convert words into vectors
but in statements positions also matters the most apart from symentic meaning

-> vector embedding -> symentic meaning
-> positional embedding -> reletion between positions


 '''

In [1]:
# cat sat on the mat
# on the mat cat sat

'''
same token ID gets mapped to same vector representation regardless of where the
token is positioned

-> position of cat -> embedded is same

'''

In [3]:
import torch

In [8]:
input = torch.tensor([1,2,2,1])

In [6]:
vector_embedding = torch.nn.Embedding(5,4)
vector_embedding

Embedding(5, 4)

In [9]:
vector_embedding(input) # <-- is not taking leverage of position

tensor([[ 0.5851, -1.0437, -0.6092,  2.7983],
        [-0.9313, -0.2746, -0.3906, -0.3042],
        [-0.9313, -0.2746, -0.3906, -0.3042],
        [ 0.5851, -1.0437, -0.6092,  2.7983]], grad_fn=<EmbeddingBackward0>)

In [ ]:
# There are 2 types of positional embeddings

'''
1/ ABSOLUTE ->

- commonly used
-> for each positio in input sequence, a unique embedding is added to token emb

x -> cat => x + y(positional) => x+y (result)
x -> cat => x + z(positional) => x+z (result)

so final embedding is different -> and encodes the position -> same dimension


-> when fix order of tokens is crucial => sequence generation -> gpt trained
and original transformer papaer is trained on this


================================================================================

2/ RELATIVE ->

- emphasis is on the relative position or distance between tokens. learns the
reletionships based on how far apart rather than at which exact position

-> can genralized better to sequence of varying length
=> sequences are very long


-> language modelling over long sequences where same phrase can appear in different part of sequence

#------------------------------------------------------------------

- makes LLM more aware about order and position
- we need to optimize for token embedding + positional embedding

=> in original paper they proposed the formula to add encoding but gpt optimized
during training process

'''

In [10]:
vocab_size = 50257
output_dim = 256  # gpt2 -> 768

token_embedding_layer = torch.nn.Embedding(vocab_size,output_dim)

In [ ]:
# dataloader and get sequence ->

In [11]:
with open('/content/drive/MyDrive/4. Data Files/LLM Dataset/the verdict.txt','r',encoding='utf-8') as f:
  raw_text = f.read()

In [12]:
import torch
import tiktoken
from torch.utils.data import Dataset, DataLoader

class GPTDatasetV1(Dataset):

  def __init__(self,text,tokenizer,max_length,stride):
    self.input_ids =[]
    self.target_ids = []

    # tokenize the entire text
    token_ids = tokenizer.encode(text,allowed_special={'<|endoftext|>'})

    # use sliding window approch to chunk book into overlapping sequence of max_length

    for i in range(0,len(token_ids)-max_length,stride): # <- range(start,end,jump)

      input_chunk = token_ids[i:i+max_length] # <-- getting chunks one by one by index
      target_chunk = token_ids[i+1 : i+max_length+1]

      self.input_ids.append(torch.tensor(input_chunk)) #<-- converting those chunks to pytorch chunks
      self.target_ids.append(torch.tensor(target_chunk))
#-------------------------------------------------------------------------------------------------------

  def __len__(self):
    return len(self.input_ids)

  def __getitem__(self, idx): # <-- dataloder requires this method <- to fetch one by one
    return self.input_ids[idx],self.target_ids[idx] #<-- returns the id's of tensors


In [14]:
def create_dataloader_v1(txt,batch_size=4,max_length=256,
                        stride=128, shuffle=True, drop_last=True,
                        num_workers=0):

  #initialize the tokenizer
  tokenizer = tiktoken.get_encoding('gpt2')

  # Create Dataset
  dataset = GPTDatasetV1(txt,tokenizer,max_length,stride)

  # crate dataloder
  dataloder = DataLoader(
      dataset,  # <-- dataset contains training and test tensors
      batch_size=batch_size, # <-- size of tensors
      shuffle=shuffle, # <-- True
      drop_last=drop_last, # <-- True
      num_workers=num_workers # <-- 0
  )

  return dataloder


In [17]:
max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size = 8, max_length= max_length,
    stride = max_length, shuffle= False
)

data_iter = iter(dataloader)
inputs,targets = next(data_iter)

In [19]:
print(inputs)
print(targets)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [21]:
# each token id we

token_embedding_layer(inputs) # each input it is going to generate embedding for each values

print(token_embedding_layer(inputs).shape) # this is the shape of

torch.Size([8, 4, 256])


In [ ]:
# +------------------------------ width = 256 ------------------------------+
# |     |     |     |     |     |     |    ...                            |
# |     |     |     |     |     |     |                                    |
# | 4 rows height                                                  (one block)
# |                                                                          |
# +--------------------------------------------------------------------------+
#    <-------------------- one block --------------------->

# Then 8 such blocks stacked in depth.


In [23]:
# add positional encoding -> as only 4 tokens are given therefore need to encode 4 only
